# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1392118875);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1392118995);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1392129435);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1392118755);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140205004602");
user_pref("browser.slowStartup.averageTime", 4838);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140205004602");
user_pref("browser.startup.homepage_override.mstone", "27.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1392217308843");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1392130908843");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4726);
user_pref("datareporting.sessions.current.main", 470);
user_pref("datareporting.sessions.current.sessionRestored", 6037);
user_pref("datareporting.sessions.current.startTime", "1392349852406");
user_pref("datareporting.sessions.current.totalTime", 11);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1392130907468,\"a\":4,\"t\":30,\"c\":true,\"m\":394,\"fp\":3121,\"sr\":3729}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1392140772442,\"a\":3,\"t\":15,\"c\":true,\"m\":416,\"fp\":3597,\"sr\":4189}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1392116389041,\"a\":4,\"t\":28,\"c\":false,\"m\":725,\"fp\":7240,\"sr\":8870}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1392118511327,\"a\":25,\"t\":324,\"c\":false,\"m\":1084,\"fp\":8390,\"sr\":10762}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1392119986728,\"a\":6,\"t\":32,\"c\":false,\"m\":706,\"fp\":5788,\"sr\":7699}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1392120998080,\"a\":38,\"t\":8983,\"c\":true,\"m\":669,\"fp\":6055,\"sr\":6627}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1392179653264,\"a\":2,\"t\":12,\"c\":true,\"m\":385,\"fp\":2913,\"sr\":3416}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1391555105000,\"rdfTime\":1391555061000}}}]");
user_pref("extensions.lastAppVersion", "27.0");
user_pref("extensions.lastPlatformVersion", "27.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140205004602");
user_pref("gecko.mstone", "27.0");
user_pref("idle.lastDailyNotification", 1392119021);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 12772);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1392349852);
user_pref("toolkit.telemetry.previousBuildID", "20140205004602");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1394722912);
